// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FormIndexController from "./form_index_controller"
application.register("form-index", FormIndexController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InvisibleHoverController from "./invisible_hover_controller"
application.register("invisible-hover", InvisibleHoverController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
