meta_product_name: "GALO"
meta_title: "Tu re - GALO"
meta_description: "Arma tu lista con tus regalos favoritos de internet en un solo lugar y compartila para que sepan que te gustaría recibir como re-GALO"
meta_image: "logos/galo_logo.png" # should exist in `app/assets/images/`
